---
- name: "[VARS] Load OS-Specific Variables"
  include_vars: "{{ ansible_os_family }}.yml"
  tags: 
    - apache
    - vhosts

- name: "[INSTALL] Main Packages"
  sudo: yes
  yum: "name={{ item }} state=present"
  with_items: apache_main_packages
  tags: 
  - apache
  - apache_install

- name: "[INSTALL] Custom Packages"
  sudo: yes
  yum: "name={{ item }} state=present"
  with_items: apache_custom_packages
  tags: 
  - apache
  - apache_install

- name: "[DIR] Ensure sites-available folder exists"
  sudo: yes
  file: "path={{ apache_vhost_available_path }} state=directory owner={{ apache_user }} group={{ apache_group }} mode=644"
  tags: 
  - apache

- name: "[DIR] Ensure sites-enabled folder exists"
  sudo: yes
  file: "path={{ apache_vhost_enabled_path }} state=directory owner={{ apache_user }} group={{ apache_group }} mode=644"
  tags: 
  - apache

- name: "[GENERATE] httpd.conf"
  sudo: yes
  template: "src=httpd.conf.j2 dest={{ apache_etc }}/conf/httpd.conf owner=root group=root mode=644"
  tags: 
  - apache
  - configs
  - httpd
  notify: 
  - Restart Apache

- name: "[GENERATE] Virtual Hosts"
  sudo: yes
  template: "src=vhost.conf.j2 dest={{ apache_etc }}/sites-available/{{ item.vhost_filename }}.conf owner=root group=root mode=0644"
  with_items: virtualhosts
  tags: 
  - apache
  - configs
  - vhosts

- name: "[LINK] All Virtual Hosts from sites-available to sites-enabled"
  sudo: yes
  file: "src={{ apache_vhost_available_path }}/{{ item.vhost_filename }}.conf dest={{ apache_vhost_enabled_path }}/{{ item.vhost_filename }}.conf state=link owner=root group=root mode=0644"
  with_items: virtualhosts
  when: item.vhost_enabled == "yes"
  tags: 
  - apache
  - configs
  - vhosts
