---
- name: start apache
  service: "name={{ apache_daemon }} state=started"

- name: restart apache
  service: "name={{ apache_daemon }} state=restarted"

- name: stop apache
  service: "name={{ apache_daemon }} state=stopped"

- name: reload apache
  service: "name={{ apache_daemon }} state=reloaded"
