---
- name: Restart Apache
  sudo: yes
  service: "name={{ apache_daemon }} state=restarted enabled=yes"

- name: Start Apache
  sudo: yes
  service: "name={{ apache_daemon }} state=started"

- name: Stop Apache
  sudo: yes
  service: "name={{ apache_daemon }} state=stopped"

- name: Reload Apache
  sudo: yes
  service: "name={{ apache_daemon }} state=reloaded"
